# Generated by Django 6.1.1 on 2026-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
    ]
